### ISSUE TITLE
Weird conflict with ath9k

### ISSUE THREAD

**Issue by yagoplx** [lwfinger/rtl8192ee#19]
I've moved over to an AR93xx card supported by ath9k for my router card, and it has been a big upgrade overall.
Unfortunately, I cannot use both cards together as AP because the rtl8192ee adapter being present will make the ath9k adapter stop beaconing completely after a while. I tried to pinpoint it to faulty hardware, but that wasn't the case.     

Since all devices in my home now support the 5ghz band, I might try again and put in both cards together in the router box so I have a fallback 2.4n AP and a hi-speed 5.0an AP. I have moved over to using my own software (https://gitlab.com/yagocl/x86routertools) over Oblique's create_ap so that I may have broader control over hostapd. Perhaps if I put the two cards under the same hostapd process it might work.      

I might start debugging this issue someday in the future, but if you have any clues to what it may be please let me know.
This issue will be here to track such progress.

**Comment by lwfinger** [comment]
I have no idea why there could be any interference. Note: I no longer support this driver. You should use the one in the kernel.

**Comment by yagoplx** [comment]
Has any work been done in the kernel driver's AP mode to make it faster? I understand if not, because this card is basically e-waste at this point. I wish it wasn't though.

-------- Mensagem Original --------
Ativo 24 de out de 2020 8:17 PM, lwfinger escreveu:

**Comment by lwfinger** [comment]
You obviously do not understand the driver history. These drivers were written by Realtek and released. I took their drivers and modified them so that they would build with all kernels and made those changes available to the public. I have no knowledge of the internal workings of the chips - you know as much as I do about them. My reason for making them available was as station devices. I have never said that they would work in AP mode or with packet injection.

The beauty of open source is that you can do whatever you want to improve it. I am winding down my career and I no longer have much interest.

**Comment by yagoplx** [comment]
Of course I do not understand, these are uncharted waters and I literally crash landed here. If I knew what I do now I'd just have returned the card while it was still possible.

Guess that's it for this card. I'll save it for a future computer build to get wireless connectivity.

-------- Mensagem Original --------
Ativo 24 de out de 2020 11:46 PM, lwfinger escreveu:
