### ISSUE TITLE
swiotlb buffer is full

### ISSUE THREAD

**Issue by yagoplx** [lwfinger/rtl8192ee#3]
rtl8192ee 0000:05:00.0: swiotlb buffer is full (sz: 4000 bytes), total 32768 (slots), used 32768 (slots)

Dmesg starts flooding with this ^

The driver works just fine for a day, but then it stops accepting new connections or responding to existing ones. Shutting the interface down by ifconfig or reloading the module 8192ee does not clean this buffer, the system has to be rebooted.

How do we get this buffer to clean itself automatically? It's pretty... annoying, but I'm not sure where to look first.

**Comment by yagoplx** [comment]
The Linux kernel has a parameter `swiotlb=` that allows us to increase this buffer. This is a viable "solution", and I will add it to the readme. 

However, it probably only delays the time where the driver will get stuck again. If that returns to happen, we might need to dig further.

Perhaps I should ask the TP-Link people for assistance with this piece of software? What do you think, Larry?

**Comment by yagoplx** [comment]
Setting the swiotlb kernel parameter did not change anything, unfortunately. The driver complained about the buffer being full, and it still was 4000 bytes large.

**Comment by lwfinger** [comment]
I agree that this driver is leaking something, but not memory. The iotlb entries are mapped using a pci_map_single() call and must be paired with a pci_unmap_single(). Unfortunately, this typical spaghetti code makes it difficult to follow the flow. My only recourse will likely be to write debug code to log each of the maps and unmaps and then manually find the ones that are not unmapped. It will take a bit of time, and I don't have it now.

**Comment by lwfinger** [comment]
Actually, I found a little time, and it was easier to analyze than I thought. The patch was as follows:
<diff --git a/hal/rtl8192e/pci/pci_ops_linux.c b/hal/rtl8192e/pci/pci_ops_linux.c
index 6014544..bda6717 100755
--- a/hal/rtl8192e/pci/pci_ops_linux.c
+++ b/hal/rtl8192e/pci/pci_ops_linux.c
@@ -79,6 +79,7 @@ static int rtl8192ee_init_rx_ring(_adapter *padapter)
                        *mapping = pci_map_single(pdev, skb_tail_pointer(skb),
                                                  precvpriv->rxbuffersize,
                                                  PCI_DMA_FROMDEVICE);
+       pr_info("**** Map #4, addr=%p\n", *mapping);
 
                        /* Reset FS, LS, Total len */
                        SET_RX_BUFFER_DESC_LS_92E(rx_desc, 0);
@@ -116,6 +117,7 @@ static void rtl8192ee_free_rx_ring(_adapter *padapter)
                                         *((dma_addr_t *) skb->cb),
                                         precvpriv->rxbuffersize,
                                         PCI_DMA_FROMDEVICE);
+       pr_info("**** Unmap addr=%p\n", *((dma_addr_t *) skb->cb));
                        kfree_skb(skb);
                }
 
@@ -182,6 +184,7 @@ static void rtl8192ee_free_tx_ring(_adapter *padapter, unsigned int prio)
                pxmitbuf = rtl8192ee_dequeue_xmitbuf(ring);
                if (pxmitbuf) {
                        pci_unmap_single(pdev, GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc), pxmitbuf->len, PCI_DMA_TODEVICE);
+       pr_info("**** Unmap addr=%p\n", GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc));
                        rtw_free_xmitbuf(pxmitpriv, pxmitbuf);
                } else {
                        RTW_INFO("%s(): qlen(%d) is not zero, but have xmitbuf in pending queue\n", __func__, ring->qlen);
@@ -306,6 +309,7 @@ void rtl8192ee_reset_desc_ring(_adapter *padapter)
                                pxmitbuf = rtl8192ee_dequeue_xmitbuf(ring);
                                if (pxmitbuf) {
                                        pci_unmap_single(pdvobjpriv->ppcidev, GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc), pxmitbuf->len, PCI_DMA_TODEVICE);
+       pr_info("**** Unmap addr=%p\n", GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc));
                                        rtw_free_xmitbuf(pxmitpriv, pxmitbuf);
                                } else {
                                        RTW_INFO("%s(): qlen(%d) is not zero, but have xmitbuf in pending queue\n", __func__, ring->qlen);
@@ -521,6 +525,7 @@ static void rtl8192ee_tx_isr(PADAPTER Adapter, int prio)
 
                if (pxmitbuf) {
                        pci_unmap_single(pdvobjpriv->ppcidev, GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc), pxmitbuf->len, PCI_DMA_TODEVICE);
+       pr_info("**** Unmap addr=%p\n", GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc));
                        rtw_sctx_done(&pxmitbuf->sctx);
                        rtw_free_xmitbuf(&(pxmitbuf->padapter->xmitpriv), pxmitbuf);
                } else
@@ -564,6 +569,7 @@ static void rtl8192ee_tx_isr(PADAPTER Adapter, int prio)
                pxmitbuf = rtl8192ee_dequeue_xmitbuf(ring);
                if (pxmitbuf) {
                        pci_unmap_single(pdvobjpriv->ppcidev, GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc), pxmitbuf->len, PCI_DMA_TODEVICE);
+       pr_info("**** Unmap addr=%p\n", GET_TX_DESC_TX_BUFFER_ADDRESS_92E(tx_desc));
                        rtw_sctx_done(&pxmitbuf->sctx);
                        rtw_free_xmitbuf(&(pxmitbuf->padapter->xmitpriv), pxmitbuf);
                } else
@@ -884,6 +890,7 @@ static void rtl8192ee_rx_mpdu(_adapter *padapter)
                                         *((dma_addr_t *)skb->cb),
                                         precvpriv->rxbuffersize,
                                         PCI_DMA_FROMDEVICE);
+       pr_info("**** Unmap addr=%p\n", ((void *)skb->cb));
 
 
                        rtl8192e_query_rx_desc_status(precvframe, skb->data);
@@ -904,6 +911,7 @@ static void rtl8192ee_rx_mpdu(_adapter *padapter)
                                rtw_free_recvframe(precvframe, &precvpriv->free_recv_queue);
                                RTW_INFO("rtl8192ee_rx_mpdu:can not allocate memory for skb copy\n");
                                *((dma_addr_t *) skb->cb) = pci_map_single(pdvobjpriv->ppcidev, skb_tail_pointer(skb), precvpriv->rxbuffersize, PCI_DMA_FROMDEVICE);
+       pr_info("**** Map #2, addr=%p\n", ((void *) skb->cb));
                                goto done;
                        }
 
@@ -919,6 +927,7 @@ static void rtl8192ee_rx_mpdu(_adapter *padapter)
                                rtw_free_recvframe(precvframe, pfree_recv_queue);
                        }
                        *((dma_addr_t *) skb->cb) = pci_map_single(pdvobjpriv->ppcidev, skb_tail_pointer(skb), precvpriv->rxbuffersize, PCI_DMA_FROMDEVICE);
+       pr_info("**** Map #3, addr=%p\n", ((void *) skb->cb));
                }
 done:
 
diff --git a/hal/rtl8192e/pci/rtl8192ee_xmit.c b/hal/rtl8192e/pci/rtl8192ee_xmit.c
index a2d0cb3..6f9486c 100755
--- a/hal/rtl8192e/pci/rtl8192ee_xmit.c
+++ b/hal/rtl8192e/pci/rtl8192ee_xmit.c
@@ -346,6 +346,7 @@ void update_txdesc_buf(struct xmit_frame *pxmitframe, u8 *pmem, s32 sz)
 
 
        mapping = pci_map_single(pdvobjpriv->ppcidev, pxmitframe->buf_addr , sz + TX_WIFI_INFO_SIZE, PCI_DMA_TODEVICE);
+       pr_info("**** Map #1, addr=%p\n", mapping);
 
        /* Calculate page size. Total buffer length including TX_WIFI_INFO and PacketLen */
        if (tx_page_size_reg > 0) {
>

Analysis: The mapped regions acquired by #1 through #3 are released very quickly. Due to some of the locking, etc., the Unmap message is logged before the Map is seen. The only different case is for #4, which maps the buffers in the RX ring. Those are not unmapped until the driver is unloaded.

The latter mapping suggests a potential problem. If other devices in your system such as the graphics card are requiring lots of DMA buffers, the IOTLB entries could be exhausted. The number is set to 128  in file include/rtw_recv.h, line 280. Try changing the 128 on that line to 64 and repeat your trials. That should be a sufficient number of RX buffers to prevent overruns.

**Comment by yagoplx** [comment]
I will test different numbers to see if they will result in a decrease/increase in performance. Probably not, because 16384K of buffer is... a bit too much. Will also test your patch. Thank you.

Not sure if you meant the patch to be like that, or it is like that, but the formatting seems wonky on here.

**Comment by lwfinger** [comment]
No, do not use my patch. I posted it only so that you could have some idea of what I did. It will overflow your dmesg buffer really quickly.

**Comment by yagoplx** [comment]
Well, thank you for trying to teach me something new. I understand your analysis, but I don't know C. Apart from applying patches and flipping knobs and switches, I'm at a loss.

**Comment by yagoplx** [comment]
I just ran a grep on my syslog and it found 20k swiotlb is full lines

**Comment by yagoplx** [comment]
As you asked, I tried out different recvbuf size settings and noted their behaviour. Here you go. A reboot was done between each one.
```

1024 -> DMA write error on recieve
486 -> DMA write error on recieve
128 -> Normal
64 > DMA write error on recieve
32 -> All packets are now martians, can't authenticate
```

**Comment by lwfinger** [comment]
Well, it was expected that bigger than 128 would make the problem worse.

Have you ever seen this problem when running the kernel, or rtlwifi_new  versions?

**Comment by yagoplx** [comment]
No, rtlwifi_new works alright for long periods of time. Except, you know, for being extremely slow as AP, and having a smaller range. It also lights up the led, which this driver doesn't do. But that's completely ignorable.

**Comment by yagoplx** [comment]
Trying out a newer kernel now to see if issue persists. Before I was using Linux 5.2 with Realtime patches. Now using regular 5.4 Linux distributed by Manjaro.

**Comment by yagoplx** [comment]
Seems to be solved by latest kernel. Haven't seen this issue anymore even with heavy usage.

**Comment by yagoplx** [comment]
After quite a while of testing, the issue only seems to have disappeared because when I upgraded the kernel **I also put in the following in the Linux commandline:**` intel_iommu=on iommu=force`. By removing these and retesting the swiotlb buffer gets full.

So the issue still exists and is not kernel dependent. The workaround lasts indefinitely but requires VT-d to be enabled by the bios.

**Comment by yagoplx** [comment]
Fixed by removing UKSM from the kernel patches. No idea what causes this behaviour with @dolohow 's uksm, but it isn't this driver. Been a few weeks and no measurable increase in baseline memory usage idle.
